### ISSUE TITLE
Can't connect WaveCell API

### ISSUE THREAD

**Issue by menthos984** [DataFire/Integrations#14]
I am trying to send a single SMS but every time I try to send one, console responds failed with status code 401.

I believe that I do not understand this part of code:
`let wavecell = require('@datafire/wavecell').create({
  username: "",
  password: ""
});`

I don't what to put here. Inputting the registered username and password doesn't seem to work.

**Comment by bobby-brennan** [comment]
I believe `username` should be your Account ID, rather than your e-mail address.

It looks like Wavecell also offers Bearer token auth - if the Account ID doesn't work, let me know and we can add Bearer auth.

**Comment by menthos984** [comment]
Hi, Thank you for your help. I tried to do your suggestions but it did not work. I contacted WaveCell too and they suggested:

> your accountID is ACCOUNT_ID. But i would advice to use API key bearer (HTTP header) to authenticate on the API. Your subaccountID is ACCOUNT_ID_1. You will need to set in the URL when calling the API

**Comment by bobby-brennan** [comment]
Marking this as fixed - let me know if we need to reopen
