### ISSUE TITLE
How to create thumbnail of Wowza Videos?

### ISSUE THREAD

**Issue by beingshashi** [DataFire/Integrations#16]
Hi,

I am looking for creating the thumbnails for all the videos which we have uploaded on Wowza.
I also want to know can we save these thumbnails on our server end, if it is possible to create thumbnails with the plugin.
I found this source link ( https://www.wowza.com/docs/how-to-generate-thumbnail-images-of-live-streams ), but this code is in JAVA. which we are not familiar with.
Need to do the same with this module.
Let me know if this is available or not?
Or is there any other way rather having java.

Thanks,

**Comment by bobby-brennan** [comment]
I would suggest asking Wowza support if they have JavaScript code for achieving something similar.
