### ISSUE TITLE
'context' var in basecamp3 api

### ISSUE THREAD

**Issue by michaelpalumbo** [DataFire/Integrations#18]
Hi there! first off thanks for providing this package! I'm running the script you provided on the readme.md page of https://www.npmjs.com/package/@datafire/basecamp

but running any of the GET requests, such as 

```javascript
let basecamp = require('@datafire/basecamp').create({
  access_token: "",
  refresh_token: "",
  client_id: "REDACTED",
  client_secret: "REDACTED",
  redirect_uri: "REDACTED"
  ApiKeyAuth: "",
  account_id: "REDACTED"
});
 
basecamp.projects.json.post({}).then(data => {
  console.log(data);
});
``` 
throws the error: 

```shell
ReferenceError: context is not defined
    at Object.<anonymous> (/Users/mp/makedoc/basecamp/basecamp.js:17:4)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

**Comment by michaelpalumbo** [comment]
hi @bobby-brennan !

I pasted your code directly and returned this: 

```shell
(node:32751) UnhandledPromiseRejectionWarning: Error: Action basecamp/projects.json.post failed with status code 404: {"status":404,"error":"Not Found"}
    at action.run.catch.e (/Users/mp/makedoc/node_modules/datafire/src/lib/integration.js:166:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32751) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asyncfunction without a catch block, or by rejecting a promise which wasnot handled with .catch(). (rejection id: 1)
(node:32751) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by michaelpalumbo** [comment]
> Can you share the code you're using (redacting credentials)? I'm unable to reproduce.

@bobby-brennan Oh sure, I just edited my original post to include the exact come I'm using. Thanks again!

**Comment by bobby-brennan** [comment]
OK great, that's exactly what I get (and makes sense since it's looking for a made up `account_id`)

I get the same error when I copy the code you added above (plus a comma after `redirect_uri`), guessing you do too.

So is it just changing one of the `REDACTED` strings to a credential string that you get the `context` error?

**Comment by michaelpalumbo** [comment]
yep, and the comma after <redirect_uri> is in my original code, but thanks for catching that here!

Should I change all redacted strings, or just one?

**Comment by bobby-brennan** [comment]
If you can find the minimal change that produces the `context` error, that would help a bunch.

Is `/Users/mp/makedoc/basecamp/basecamp.js` the file that contains this code?

**Comment by michaelpalumbo** [comment]
yep, i'll try each one. just a moment

**Comment by bobby-brennan** [comment]
Yes, you need an `access_token` to get in.

To get an `access_token`, you can run `datafire autenticate basecamp` (you'll need to install datafire with `npm i -g datafire` first)

**Comment by michaelpalumbo** [comment]
> Just to confirm, /Users/mp/makedoc/basecamp/basecamp.js is the file containing the code you're running?
yep!

> The 401 error, or the original context error?

the context error comes in whenever I try a GET request i.e. after the basecamp auth

```javascript
basecamp.people.json.get(null, context)
```

**Comment by michaelpalumbo** [comment]
ohhhh

**Comment by bobby-brennan** [comment]
That command will generate an account, `DataFire-accounts.yml`, with you access token

**Comment by michaelpalumbo** [comment]
which directory should i run:
```shell 
datafire autenticate basecamp
```
?

**Comment by bobby-brennan** [comment]
The `context` error shows up because you haven't defined `context`. You can delete it there (in which case it will use the credentials passed to create), or you can create a context with:

```js
var datafire = require('datafire');
var context = new datafire.Context({
  accounts: {
    basecamp: {
      "account_id": "42",
      /* etc */
    }
  }
})
```

**Comment by bobby-brennan** [comment]
You can run in any directory. It will create the DataFire-accounts.yml in that directory.

**Comment by michaelpalumbo** [comment]
ok. so now that i've done that, and copied over the new credentials, how do I run the localhost:3333 server? I assume datafire needs to run?

**Comment by michaelpalumbo** [comment]
thanks so much for your help btw :D

**Comment by bobby-brennan** [comment]
No prob!

It's already listening on `localhost:3333` while that link is up - no need to start your own server

**Comment by michaelpalumbo** [comment]
actually it is no longer running

**Comment by bobby-brennan** [comment]
Did the command exit?

I forgot, you do need to add `http://localhost:3333` to your list of Redirect URIs in Basecamp settings (wherever you got the `client_id`) 

The command `datafire authenticate` will show a link once you are done with the prompts. If you visit that link and sign into your account, it'll redirect you back to `localhost:3333`, stash your credentials in `DataFire-accounts.yml`, and the command will exit.

**Comment by michaelpalumbo** [comment]
yep, i had added that already, the stdout in CLI told me to do so! but thanks! :D

**Comment by michaelpalumbo** [comment]
ah ok, so I went through all of that already :)

**Comment by bobby-brennan** [comment]
OK cool - are you still stuck? Did the token make it into DataFire-accounts.yml?

**Comment by michaelpalumbo** [comment]
yep, and i'm still stuck. I'l note that I don't have anything to enter for 
```javascript
  ApiKeyAuth: "",
```
and, that attempting to run the script and asking:

```javascript
basecamp.projects.json.post({}).then(data => {
  console.log(data);
});
```
returns the following 

```shell
(node:33254) UnhandledPromiseRejectionWarning: Error: Action basecamp/projects.json.post failed with status code 401:
    at action.run.catch.e (/Users/mp/makedoc/node_modules/datafire/src/lib/integration.js:166:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:33254) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promisewhich was not handled with .catch(). (rejection id: 1)
(node:33254) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zeroexit code.
```

**Comment by bobby-brennan** [comment]
`ApiKeyAuth` you can ignore - that's an alternative to oauth

Did you paste the access_token into basecamp.js?

**Comment by michaelpalumbo** [comment]
yep i sure did!

**Comment by michaelpalumbo** [comment]
oh hangon. there's a difference in the access/refresh tokens as stated in the localhost:3333 and in the datafire-accounts.yml. the latter added "=--" followed by an additional string of ~64 characters

**Comment by bobby-brennan** [comment]
Hrm. 

```js
let basecamp = require('@datafire/basecamp').create({
  access_token: "YOUR_ACCESS_TOKEN",
  account_id: "YOUR_ACCOUNT_ID",
});
```

Should be all you need.

**Comment by michaelpalumbo** [comment]
which one should I paste? I had used the one from localhost:3333 originally

**Comment by michaelpalumbo** [comment]
ok i'll try that at the moment

**Comment by bobby-brennan** [comment]
Both my `access_token` and `refresh_token` contain a `=--` somewhere in the middle - be sure to include that and whatever follows

**Comment by michaelpalumbo** [comment]
ok, some progress maybe:

```shell
(node:33326) UnhandledPromiseRejectionWarning: Error: Action basecamp/projects.json.post failed with status code 400: {"status":400,"error":"Bad Request"}
    at action.run.catch.e (/Users/mp/makedoc/node_modules/datafire/src/lib/integration.js:166:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:33326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promisewhich was not handled with .catch(). (rejection id: 1)
(node:33326) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zeroexit code.
```

**Comment by bobby-brennan** [comment]
Great!

Try `basecamp.projects.json.post({name: "foo"})`

**Comment by bobby-brennan** [comment]
actually, `basecamp.projects.json.post({body: {name: "foo"}})

**Comment by michaelpalumbo** [comment]
```shell
(node:33335) UnhandledPromiseRejectionWarning: Error: data should NOT have additional properties
    at module.exports.Action.run (/Users/mp/makedoc/node_modules/datafire/src/lib/action.js:91:17)
    at Object.obj.(anonymous function) [as post] (/Users/mp/makedoc/node_modules/datafire/src/lib/integration.js:158:23)
    at Object.toObj.(anonymous function) [as post] (/Users/mp/makedoc/node_modules/datafire/src/lib/integration-instance.js:23:32)
    at Object.<anonymous> (/Users/mp/makedoc/basecamp/basecamp.js:22:24)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
(node:33335) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promisewhich was not handled with .catch(). (rejection id: 2)
(node:33335) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zeroexit code.
```

**Comment by michaelpalumbo** [comment]
oh ok, i'll try what you just send

**Comment by michaelpalumbo** [comment]
oh wait, can we stick with 'get' requests? i don't want to inject data into my team's activity haha

**Comment by bobby-brennan** [comment]
Haha yeah, `basecamp.my.profile.json.get({})` should work fine

**Comment by michaelpalumbo** [comment]
YESSSS

**Comment by bobby-brennan** [comment]
Awesome! I'm gonna close this issue and sign off for now, but feel free to ping if you run into any more trouble.

**Comment by michaelpalumbo** [comment]
Thanks again @bobby-brennan 
last question. and its a security one. i assume i can continue to develop my script using this access token on my own, but I assume I don't want to let them use a script that means they could post on my behalf... so do they need to go through the same datafire authentication for their own user accounts on basecamp? i assume the answer is yes, and its fine if it is! -- just need to know what to plan ahead for :D

**Comment by bobby-brennan** [comment]
Yup! You're exactly right. You shouldn't share your access token.

If you want you write scripts that post to Basecamp, I'd suggest creating a
"datafire bot" account, and sharing tokens from that account.

You can also scope your tokens to only have a limited set of permissions
using the "scopes" input.
