### ISSUE TITLE
How to generate openAPI specs

### ISSUE THREAD

**Issue by kvnamipara** [DataFire/Integrations#19]
I was recently got curious about open APIs. 1. How did one can generate the open API specs even if the integration service companies didn't provide one? 2. How can one generate an open API spec from REST APIs if no other info is available other than documentation? Thank you.

**Comment by bobby-brennan** [comment]
Hi there,

We use a variety of methods for generating Open API specs:
* Some are published by the API owner
* Some are [converted from another spec](https://github.com/LucyBot-Inc/api-spec-converter) format published by the API owner
* Some are scraped using [this package](https://github.com/bobby-brennan/scrape-to-swagger), which uses jQuery-style selectors to turn HTML documentation into OpenAPI

DataFire also offers professional services for generating OpenAPI specs and DataFire integrations if there are particular APIs you need.

-Bobby

**Comment by kvnamipara** [comment]
thanks
