### ISSUE TITLE
Integration with JIRA requires username and password

### ISSUE THREAD

**Issue by codecraf8** [DataFire/Integrations#27]
In your code, you mention to activate JIRA, one should instantiate using username, and password to be sent to those calls, can we do without it? Just plain old, oauth token?

**Comment by bobby-brennan** [comment]
Yes, you can specify `access_token`, [as seen here](https://github.com/DataFire/Integrations/tree/master/integrations/generated/jira).

I would also recommend setting `refresh_token`, `client_id`, and `client_secret` unless your `access_token` doesn't expire.
