### ISSUE TITLE
[ Basecamp3 ] Missing replies in inbox_forwards's endpoint

### ISSUE THREAD

**Issue by jjperezaguinaga** [DataFire/Integrations#30]
As described in the [Basecamp API repository](https://github.com/basecamp/bc3-api/issues/213), it seems we have an option to request the replies from the `inbox_forward` endpoint. However, the current Basecamp integration doesn't have that feature implemented.

As comments for other records within Basecamp, it would be great to have those as well.

**Comment by bobby-brennan** [comment]
Thanks! We scrape their documentation to generate an Open API spec - once their docs are updated with this endpoint, feel free to ping this thread and we can pull in the changes.

**Comment by jjperezaguinaga** [comment]
@bobby-brennan will do! Got a response from [them](https://github.com/basecamp/bc3-api/issues/213#issuecomment-471038427), so I'll update it here when their docs are updated.

**Comment by jjperezaguinaga** [comment]
@bobby-brennan quick update, Basecamp just added [inbox replies](https://github.com/basecamp/bc3-api/blob/master/sections/inbox_replies.md#inbox-replies) to their documentation 🎉

**Comment by bobby-brennan** [comment]
Sorry for the delay - should be working now in `@datafire/basecamp@3.0.0`. Let me know if you run into any trouble!
