### ISSUE TITLE
SMTP integration friendly names

### ISSUE THREAD

**Issue by rion18** [DataFire/Integrations#33]
Hi! I'm currently using datafire to use some of your awesome integrations. When using the SMTP integration however, it seems there's no way to send friendly names on the `to` or the `from` fields. I've seen that Datafire's SMTP integration uses Nodemailer's SMTP Connection as its underlying technology, which apparently doesn't allow this. Maybe this integration could use Nodemailer (instead of SMTP Connection) as defined here: https://nodemailer.com/smtp/envelope/ .

**What's expected:**
Using the following:

```
let smtp = require('@datafire/smtp').create({
  host: "",
  port: "",
  username: "",
  password: ""
});

smtp.send({
  "from": "Example Sender <example@mail.com>",
  "to": []
}).then(data => {
  console.log(data);
});
```

It should allow me to send an email with "Example Sender" as friendly name and "example@mail.com" as its email.

**What happens:**

We get an "Invalid sender" error.

**If you guys agree, I could issue a PR with this since it could be something useful.**

**Comment by bobby-brennan** [comment]
Hi there,

This seems like a great idea. Would happily accept a PR to this effect.

Thanks!

**Comment by rion18** [comment]
@bobby-brennan Issued PR 36: https://github.com/DataFire/Integrations/pull/36
