### ISSUE TITLE
specify url cache duration time in DataFire.yml for endpoint

### ISSUE THREAD

**Issue by coderofsalvation** [DataFire/Integrations#4]
Just an idea:

```
# DataFire.yml
paths:
  /hello:
    get:
      action: ./function/hello
      cache: 5
```

Many times i find myself caching endpoint responses to prevent expense async calls / speed up responses.
I usually use this middleware module `cache.js`:

```
var mcache = require('memory-cache');

// usage: 
//   var cache = require('cache')
//   app.get("/foo/bar*", cache(5) ) // cache 5 seconds
 
module.exports = (duration) => {
  return (req, res, next) => {
    let key = JSON.stringify({method:req.method, url:req.url, query:req.query, body:req.body, headers:req.headers })
    let cachedBody = mcache.get(key)
    if (cachedBody) {
      res.header(cachedBody.headers)
      res.send(cachedBody.body)
      return
    } else {
      res.sendResponse = res.send
      res.send = (body) => {
        var obj = {body:body, headers:res.header()._headers}
        mcache.put(key, obj, duration * 1000);
        res.sendResponse(body)
      }
      next()
    }
  }
}
``` 
Is this something which might be interesting to include in the datafire module?
It might also give the public datafire.io-server some headroom.

cheers

**Comment by bobby-brennan** [comment]
This is a great idea, I think many would find it useful. Mind re-opening the issue in the [main DataFire repo](https://github.com/DataFire/DataFire/issues)?

I'll try and tackle it sometime this/next week. If you need it sooner, feel free to send a PR - should just need to add the above logic to src/lib/project-server.js

**Comment by coderofsalvation** [comment]
agreed, moved to https://github.com/DataFire/DataFire/issues/27
