### ISSUE TITLE
Can anyone provide some insight on the "context" argument in the methods?

### ISSUE THREAD

**Issue by SLYtiger16** [DataFire/Integrations#41]
As stated I have reviewed the code and the RFC and I guess I am confused on what the "context" is and how to utilize it?
`caldav.listEvents({
  "filename": ""
}, **context**)`

**Comment by rbren** [comment]
`context` is an optional argument. In particular, it can contain authentication details if those weren't passed into the constructor. If you're building your own custom actions, it will have details about the triggering event (e.g. HTTP headers)
