### ISSUE TITLE
@datafire/mailchimp api version 1.3 is no more working.

### ISSUE THREAD

**Issue by git2dfc** [DataFire/Integrations#5]
should change mailchimp api version to 3.0
Or create new @datafire/mailchimp3

**Comment by bobby-brennan** [comment]
Which version of `@datafire/mailchimp` are you working with? Some fixes were pushed in 3.0.0.

I'm able to use the mailchimp client successfully with my account, but it was created when 1.3 was still supported. Regardless we should update to 3.0.

**Comment by git2dfc** [comment]
1.3 is not working for me (maybe my MailChimp account just support 3.0)
I have tried to use curl connect to MailChimp 1.3 -- not working.

changing openapi.josn --- make to use 3.0 which is working.

I have tried ""datafire integrate --openapi http://api.mailchimp.com/schema/3.0/Swagger.json --name mailchimp30"
get invalid Swagger so maybe datafire itegrate does not support openapi josn with external files or urls.

Dong

**Comment by bobby-brennan** [comment]
OK, looks like the issue is the external files. I've added some logic to resolve external $refs, but swagger-parser seems to be triggering a rate limit and is unable to download every resource.

Regardless, should be able to add Mailchimp 3.0 support in the next day or so.

**Comment by bobby-brennan** [comment]
Good news: Mailchimp 3.0 support is published in @datafire/mailchimp@4.0.0

If you spot any problems feel free to open another issue here.

Thanks for the report!
