### ISSUE TITLE
Redmine x Visual Studio Team Services

### ISSUE THREAD

**Issue by cloudcon** [DataFire/Integrations#7]
Hey Guys,
Unfortunately I do not understand anything about NODEJS and about this part of integrations, I was wondering if it would be possible to create the integration between Redmine and Visual studio team services.
Same as Zarpier's
https://zapier.com/zapbook/redmine/visual-studio-online/
Thanks :)

**Comment by bobby-brennan** [comment]
Hi,

It looks like Open API is available for redmine:

https://github.com/komikoni/redmine-swagger

We should be able to add that integration no problem.

It looks like VSTS offers a node client:

https://github.com/Microsoft/vsts-node-api/blob/master/README.md

So it should be possible to write a datafire wrapper around it. They
include .d.ts type files so input/output schemas can be built add well.

I will work on adding redmine this week, and see what would be involved in
creating a wrapper for vsts.

-Bobby


On Aug 21, 2017 8:54 AM, "Cloudcon" <notifications@github.com> wrote:

Hey Guys,
Unfortunately I do not understand anything about NODEJS and about this part
of integrations, I was wondering if it would be possible to create the
integration between Redmine and Visual studio team services.
Same as Zarpier's
https://zapier.com/zapbook/redmine/visual-studio-online/
Thanks :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/DataFire/Integrations/issues/7>, or mute the thread

**Comment by cloudcon** [comment]
Thank you very much my friend, I will be eternally grateful if you can do it, and if you need someone to translate the system, you can count on me.
Thank you again

**Comment by bobby-brennan** [comment]
Created a Redmine integration today:

https://github.com/DataFire/Integrations/tree/master/integrations/generated/redmine

Give it a shot and let me know if you spot any issues.

For VSTS, I'd recommend using the [vsts-node-api library](https://github.com/Microsoft/vsts-node-api). It uses promises already, so it should be easy to incorporate into any DataFire project.

Good luck!

-Bobby

**Comment by cloudcon** [comment]
Thanks man, 
I will try install both here and give you feedback.
Thanks again

**Comment by cloudcon** [comment]
Hello,

unfortunately I could not do the integration between redmine and visual studio.

I would like that when inserting an Issue in redimine a task was created in Visual Studio to be able to integrate the source code to the ticket.

Many thanks for your attention again.

I apologize for my limitations.

 

 

 

------+

 


 <http://www.cloudcon.com.br/> 

André Faria / CEO 
 <mailto:andre@cloudcon.com.br> andre@cloudcon.com.br / (27) 99901-5666

Cloudcon Tecnologia 
 <http://www.cloudcon.com.br/> www.cloudcon.com.br

 <https://twitter.com/coudcon>   <https://plus.google.com/+CloudconBres>   <https://htmlsig.com/skype?username=cloudcon-es> 

	
	
	

 

 

De: Bobby Brennan [mailto:notifications@github.com] 
Enviada em: quinta-feira, 24 de agosto de 2017 17:44
Para: DataFire/Integrations <Integrations@noreply.github.com>
Cc: Cloudcon <andre@cloudcon.com.br>; Author <author@noreply.github.com>
Assunto: Re: [DataFire/Integrations] Redmine x Visual Studio Team Services (#7)

 

Created a Redmine integration today:

https://github.com/DataFire/Integrations/tree/master/integrations/generated/redmine

Give it a shot and let me know if you spot any issues.

For VSTS, I'd recommend using the vsts-node-api library <https://github.com/Microsoft/vsts-node-api> . It uses promises already, so it should be easy to incorporate into any DataFire project.

Good luck!

-Bobby

**Comment by bobby-brennan** [comment]
We've actually just added [a new feature](https://github.com/DataFire/DataFire#monitors) that should make this much easier. If you upgrade to datafire@2.16.0, the instructions below should work.

First, create a task in DataFire.yml that will monitor Redmine tasks:
```yaml
tasks:
  monitor_issues:
    schedule: rate(5 minutes)
    action: ./new-visual-studio-task.js
    monitor:
      action: redmine/issues.json.get
      input:
        sort: created_on
        # you can add project_id, status_id, etc here
      array: issues
      trackBy: id
```

This says, every 5 minutes, run the action `redmine/issues.json.get`, look at the `issues` array in the response, and keep track of each `id`. When a new issue is found, it will be passed to ./create-vs-task.js (below). Note that only new issues will be passed in - existing issues will be ignored.

Next we create ./new-visual-studio-task.js:

```js
let datafire = require('datafire');
let vsts = require('vso-node-api');
let collectionUrl = "https://fabrikam.visualstudio.com/defaultcollection";
let authHandler = vsts.getPersonalAccessTokenHandler("YOUR_TOKEN"); 
let connect = new vsts.WebApi(collectionUrl, authHandler);    
let taskAgent = connect.getTaskAgentApi();

module.exports = new datafire.Action({
  handler: input => {
    console.log('found new issue: ' + input.subject + '\n' + input.description)
    return taskAgent.uploadTaskDefinition(...);
  }
})
```

I haven't looked at the specifics of the [vsts library](https://github.com/Microsoft/vsts-node-api), but you'll just need to figure out what to pass to `uploadTaskDefinition` (or whatever the approprate VSTS call is).

Hope that helps!

**Comment by cloudcon** [comment]
Thanks a lot my friend.

Work like charm J

 

You are amazing !!!!!!!!!!!!!!

 

 

 

##------ 

 


 <http://www.cloudcon.com.br/> 

André Faria / CEO 
 <mailto:andre@cloudcon.com.br> andre@cloudcon.com.br / (27) 99901-5666

Cloudcon Tecnologia 
 <http://www.cloudcon.com.br/> www.cloudcon.com.br

 <https://twitter.com/coudcon>   <https://plus.google.com/+CloudconBres>   <https://htmlsig.com/skype?username=cloudcon-es> 

	
	
	

 

 

De: Bobby Brennan [mailto:notifications@github.com] 
Enviada em: terça-feira, 12 de setembro de 2017 16:07
Para: DataFire/Integrations <Integrations@noreply.github.com>
Cc: Cloudcon <andre@cloudcon.com.br>; Author <author@noreply.github.com>
Assunto: Re: [DataFire/Integrations] Redmine x Visual Studio Team Services (#7)

 

We've actually just added a new feature <https://github.com/DataFire/DataFire#monitors>  that should make this much easier. If you upgrade to datafire@2.16.0 <mailto:datafire@2.16.0> , the instructions below should work.

First, create a task in DataFire.yml that will monitor Redmine tasks:

tasks:
  monitor_issues:
    schedule: rate(5 minutes)
    action: ./new-visual-studio-task.js
    monitor:
      action: redmine/issues.json.get
      input:
        sort: created_on
        # you can add project_id, status_id, etc here
      array: issues
      trackBy: id

This says, every 5 minutes, run the action redmine/issues.json.get, look at the issues array in the response, and keep track of each id. When a new issue is found, it will be passed to ./create-vs-task.js (below). Note that only new issues will be passed in - existing issues will be ignored.

Next we create ./new-visual-studio-task.js:

let datafire = require('datafire');
let vsts = require('vso-node-api');
let collectionUrl = "https://fabrikam.visualstudio.com/defaultcollection";
let authHandler = vsts.getPersonalAccessTokenHandler("YOUR_TOKEN"); 
let connect = new vsts.WebApi(collectionUrl, authHandler);    
let taskAgent = connect.getTaskAgentApi();
 
module.exports = new datafire.Action({
  handler: input => {
    console.log('found new issue: ' + input.subject + '\n' + input.description)
    return taskAgent.uploadTaskDefinition(...);
  }
})

I haven't looked at the specifics of the vsts library <https://github.com/Microsoft/vsts-node-api> , but you'll just need to figure out what to pass to uploadTaskDefinition (or whatever the approprate VSTS call is).

Hope that helps!
